### ISSUE TITLE
Code Doesn't show any exception when Solace Server is not connected ...

### ISSUE THREAD

**Issue by arvindonnet** [SolaceSamples/solace-samples-amqp-nodejs#24]
Code Doesn't show any exception when Solace Server is not connected ...is there a way to trap this exception.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️

Please go to the [Solace Community](https://solace.community) for general discussions :)
