### ISSUE TITLE
I dont's see any way to create connection session and keep connection live..for AMQP10

### ISSUE THREAD

**Issue by arvindonnet** [SolaceSamples/solace-samples-amqp-nodejs#25]
I dont's see any way to create connection session and keep connection live..for AMQP10 
Plase help.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️

Please go to the [Solace Community](https://solace.community) for general discussions :)
