### ISSUE TITLE
Instruction to create the queue "Q/Tutorial" lacking

### ISSUE THREAD

**Issue by lwyic** [SolaceSamples/solace-samples-amqp-nodejs#5]
I lacks the instruction to create the queue "Q/Tutorial" first.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️

Please go to the [Solace Community](https://solace.community) for general discussions :)
