### ISSUE TITLE
Can we send to a topic? instead of a Queue Endpoint?

### ISSUE THREAD

**Issue by lwyic** [SolaceSamples/solace-samples-amqp-nodejs#6]
The tutorial talks about sending to and receiving from a queue. Can we send messages to just a "topic"?

**Comment by jschabowsky** [comment]
The tutorials will be updated after we make it easier for a nodejs client easier to send/receive from a topic. This is a known limitation that is actively being worked outside of this issue.

**Comment by mdspielman** [comment]
As outlined by @jschabowsky, this issue is actively being worked on by Solace. This issue will be updated once a solution is available.

**Comment by mfisch04** [comment]
Is there an update to this issue?  We would like to use the node AMQP library to publish to a topic.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
